// ========================================================================
// DATA — 题目数据集中管理（来源：大英二1-4单元 3、6题及翻译）
// ========================================================================

// 选词填空数据 (mcData) — 课后3
const mcData = [
    // ── Unit 1 ──
    { unit:1, clue:"decided to ___ his speech", sentence:"The guest speaker decided to ______ his speech in order to leave enough time for his audience to ask questions.", ans:"condense", cn:"压缩", hint:"压缩演讲" },
    { unit:1, clue:"capacity has ___ the previous level", sentence:"According to the media, China's wind power capacity has ______ the previous level considerably.", ans:"exceed", filled:"exceeded", cn:"超过", hint:"超过水平" },
    { unit:1, clue:"negative consequences of a sleep ___", sentence:"Researchers conducted a set of psychological tests to determine the negative consequences of a sleep ______.", ans:"deficit", cn:"不足", hint:"睡眠不足" },
    { unit:1, clue:"can ___ more than 10 odors", sentence:"In addition to a sense of sight, bees also have an unusual sense of smell, so they can ______ more than 10 similar flower odors.", ans:"distinguish", cn:"区分", hint:"区分气味" },
    { unit:1, clue:"most important ___ in my life", sentence:"Moving forward even in the face of great difficulties has become the most important ______ in my life and career.", ans:"asset", cn:"财富/资产", hint:"重要资产" },
    { unit:1, clue:"must be ___ supported by evidence", sentence:"The lawyer proclaimed that they couldn't jump to conclusions because acceptable conclusions must be ______ supported by evidence.", ans:"adequately", cn:"充分地", hint:"足够证据" },
    { unit:1, clue:"not ___ in social interactions", sentence:"To help the employees become more communicative, the company offered several workshops to those who were not ______ in social interactions.", ans:"competent", cn:"能胜任的", hint:"社交胜任" },
    { unit:1, clue:"have in ___ to college life", sentence:"Some parents try to help solve the problems that their sons and daughters have in ______ to their college life.", ans:"adjust", filled:"adjusting", cn:"适应", hint:"适应大学" },
    { unit:1, clue:"a series of ___ measures", sentence:"China's series of ______ measures have proved to be effective for a steady economic recovery despite difficulties.", ans:"precise", cn:"精确的", hint:"精准措施" },
    { unit:1, clue:"demonstrated his Chinese ___", sentence:"The Italian businessman spoke fluent Chinese and demonstrated his Chinese ______ at the World Expo held in Shanghai.", ans:"proficiency", cn:"熟练/水平", hint:"中文水平" },

    // ── Unit 2 ──
    { unit:2, clue:"the ___ global fight", sentence:"With the ______ global fight against poverty still continuing, many countries are looking to draw inspiration from China.", ans:"prolonged", cn:"长期的", hint:"长期斗争" },
    { unit:2, clue:"news ___", sentence:"According to the news ______, her interest in writing about plants and animals came from her childhood.", ans:"release", cn:"发布/新闻稿", hint:"新闻发布" },
    { unit:2, clue:"develop their ___ interests", sentence:"Many of them are beginners who have never done painting before and are looking to develop their ______ interests.", ans:"artistic", cn:"艺术的", hint:"艺术兴趣" },
    { unit:2, clue:"people ___ and shopping", sentence:"Consumers are increasingly comfortable shopping using their mobile devices, with 69 percent of people ______ and shopping online last year.", ans:"browse", filled:"browsing", cn:"浏览", hint:"浏览购物" },
    { unit:2, clue:"at the ___ of the Great Wall", sentence:"The tourists were awestruck at the ______ of the Great Wall, the building of which started as early as the seventh century B.C.E.", ans:"magnificence", cn:"宏伟壮观", hint:"宏伟长城" },
    { unit:2, clue:"better treatment ___", sentence:"As we know, earlier diagnosis can give better treatment ______ to patients, which will also help them get effective care.", ans:"option", filled:"options", cn:"选择", hint:"治疗选项" },
    { unit:2, clue:"___ their appointments", sentence:"Some clinics require people to call the front desk to ______ their appointments before they come to see the doctors.", ans:"confirm", cn:"确认", hint:"确认预约" },
    { unit:2, clue:"this very ___ site", sentence:"The website is reliable because I've made dozens of purchases from this very ______ site with zero problems.", ans:"reputable", cn:"信誉好的", hint:"信誉网站" },
    { unit:2, clue:"___ serious analysis", sentence:"\u201CWhat do you think the author meant when \u2026?\u201D is a common book club question, which ______ serious analysis of a topic.", ans:"provoke", filled:"provokes", cn:"引发", hint:"引发分析" },
    { unit:2, clue:"inspiration and ___", sentence:"Just as we all admire heroes, we look to others for inspiration and ______, but change has to start with you, as an individual.", ans:"aspiration", cn:"志向", hint:"灵感和志向" },

    // ── Unit 3 ──
    { unit:3, clue:"schedule is completely ___", sentence:"The boss said, \u201CThe schedule is completely ______ because I do not need to be around and watch when you do your work.\u201D", ans:"flexible", cn:"灵活的", hint:"日程灵活" },
    { unit:3, clue:"growth will ___ the economy", sentence:"Currently, the stock market is not very stable, but over the long run, the growth of stock funds will ______ the growth of the economy.", ans:"parallel", cn:"与…并行", hint:"与经济增长并行" },
    { unit:3, clue:"how to perform any ___ work", sentence:"These student volunteers can decide how to perform any ______ work, for which they are qualified and have a strong passion.", ans:"assign", filled:"assigned", cn:"分配的", hint:"分配的任务" },
    { unit:3, clue:"___ natural behaviors", sentence:"Human beings, by providing environmental enrichment, encourage animals to explore, interact, and ______ natural behaviors.", ans:"exhibit", cn:"展现", hint:"展现天性" },
    { unit:3, clue:"qualities like ___", sentence:"Along with extraordinary courage, qualities like ______, teamwork, and most importantly, leadership shine in all of our student activities.", ans:"persistence", cn:"坚持", hint:"坚持不懈" },
    { unit:3, clue:"architecturally ___ buildings", sentence:"This is a beautiful part of the city to live in, with stylish and architecturally ______ historic buildings lining the clean and quiet streets.", ans:"stunning", cn:"令人惊叹的", hint:"惊人建筑" },
    { unit:3, clue:"___ a qualified person", sentence:"An energetic search will soon be put in place to ______ a qualified person who can continue with the leadership of a big company.", ans:"recruit", cn:"招募", hint:"招募人才" },
    { unit:3, clue:"___ hardships throughout my life", sentence:"I've ______ hardships throughout my life, so I think I can handle the stress and achieve my full potential in this company.", ans:"endure", filled:"endured", cn:"忍受", hint:"忍受艰辛" },
    { unit:3, clue:"___ exercise and outdoor sports", sentence:"Many people believe that ______ exercise and outdoor sports could better help people stay healthy and strong.", ans:"vigorous", cn:"剧烈的", hint:"剧烈运动" },
    { unit:3, clue:"all of my ___ doubts", sentence:"With the help of my family and friends, all of my ______ doubts about myself gradually disappeared and my confidence was restored.", ans:"internal", cn:"内心的", hint:"内心疑虑" },

    // ── Unit 4 ──
    { unit:4, clue:"surgery is ___ performed", sentence:"According to medical doctors, if a patient's tumor is small, surgery is ______ performed to remove it.", ans:"typical", filled:"typically", cn:"通常", hint:"通常手术" },
    { unit:4, clue:"deep-water ocean ___", sentence:"These graduates brought deep-water ocean ______ technology to the region to help explore the areas.", ans:"survey", cn:"勘测", hint:"海洋勘测" },
    { unit:4, clue:"jot down ___ ideas", sentence:"Here is my suggestion in terms of writing process: Before you start writing an essay, just jot down ______ ideas to do brainstorming.", ans:"random", cn:"随机的", hint:"随意想法" },
    { unit:4, clue:"___ their performance", sentence:"It is important for athletes to have rigorous physical and technical training to ______ their performance in sports competitions.", ans:"maximize", cn:"最大化", hint:"最大化表现" },
    { unit:4, clue:"___ the academic requirements", sentence:"After successful completion of these courses, students will have mostly ______ the academic requirements for their undergraduate studies.", ans:"fulfill", filled:"fulfilled", cn:"完成", hint:"完成要求" },
    { unit:4, clue:"said so ___", sentence:"Only three short straightforward words, but they were said so ______ that all the audience were impressed.", ans:"resolute", filled:"resolutely", cn:"坚决地", hint:"说得坚决" },
    { unit:4, clue:"key ___ projects", sentence:"This position would ideally suit candidates who have exposure to working on key ______ projects, preferably in the area of geophysics.", ans:"strategic", cn:"战略的", hint:"战略项目" },
    { unit:4, clue:"a(n) ___ opportunity", sentence:"Internship, which gives you valuable work experience, can offer you a(n) ______ opportunity to be competitive in the job market.", ans:"exceptional", cn:"非凡的", hint:"绝佳机会" },
    { unit:4, clue:"his ___ the dream", sentence:"He understood that his ______ the dream was not for himself but for the people who had the same hopes and passions as him.", ans:"chase", filled:"chasing", cn:"追逐", hint:"追逐梦想" },
    { unit:4, clue:"very ___ instructions", sentence:"He gave us very ______ instructions on how to handle the new machine, so we all understood what he meant.", ans:"explicit", cn:"明确的", hint:"明确指示" },
];

// 短语完形数据 (expData) — 课后6
const expData = [
    // ── Unit 1 ──
    { unit:1, clue:"so they ___ contact or visit", sentence:"In Chinese culture, adult children are expected to take care of their aged parents, so they ______ contact or visit their parents regularly.", ans:"be obliged to", filled:"are obliged to", cn:"有义务", hint:"有义务做" },
    { unit:1, clue:"won't ___ avoiding them", sentence:"Most of the time, people don't really care about natural disasters and won't ______ avoiding them till they are personally affected by one.", ans:"get serious about", cn:"认真对待", hint:"认真对待" },
    { unit:1, clue:"When you ___ a friend", sentence:"When you ______ a friend that you haven't seen for a long time and have a good chat with him or her, you will surely be delighted.", ans:"run into", cn:"偶遇", hint:"偶遇朋友" },
    { unit:1, clue:"need to ___ facts and opinions", sentence:"While reading, we need to ______ facts and opinions in order to have a better and more accurate comprehension.", ans:"distinguish between", cn:"区分", hint:"区分事实和观点" },
    { unit:1, clue:"products ___ the fields", sentence:"The growth of the food e-commerce sector in China has played an important role in promoting the sales of agricultural products ______ the fields.", ans:"fresh from", cn:"刚从…来", hint:"新鲜采摘" },
    { unit:1, clue:"I ___ them (don't like)", sentence:"If I don't like someone or something, I might just say I ______ them, even though it sounds a little rude.", ans:"be allergic to", filled:"am allergic to", cn:"对…反感", hint:"反感某人" },
    { unit:1, clue:"I quickly ___ (discussion)", sentence:"When the topic was discussed, I quickly ______ because I am not good at things like math and analytical skills.", ans:"get lost", filled:"got lost", cn:"迷失/跟不上", hint:"跟不上讨论" },
    { unit:1, clue:"companies will ___ this town", sentence:"It is hoped that some companies will ______ this small old town to invest and build factories.", ans:"become attracted to", cn:"被吸引", hint:"被小镇吸引" },
    { unit:1, clue:"is ___ a golden age", sentence:"The Tang Dynasty is ______ a golden age in Chinese history, when Chinese culture spread across much of Asia.", ans:"look upon ... as", filled:"looked upon as", cn:"被视为", hint:"被视为黄金时代" },

    // ── Unit 2 ──
    { unit:2, clue:"I was ___ (scenery)", sentence:"When I first saw the scenery of Mount Huangshan, I was ______ : the fascinating pine trees, the spectacular peaks, and the fairyland of clouds and mists.", ans:"in awe", cn:"敬畏", hint:"心生敬畏" },
    { unit:2, clue:"ideas and suggestions ___", sentence:"The group discussion became heated, with creative ideas and suggestions ______ from time to time.", ans:"throw ... out", filled:"thrown out", cn:"提出", hint:"抛出想法" },
    { unit:2, clue:"don't want to ___", sentence:"Whenever there is a chance we can help these children, we make a top effort and don't want to ______.", ans:"let sb. down", filled:"let them down", cn:"让某人失望", hint:"不让人失望" },
    { unit:2, clue:"it ___ fantastic", sentence:"I had never been to this restaurant before, but it ______ fantastic not only because of its delicious food but also the wonderful service.", ans:"turn out", filled:"turned out", cn:"结果证明", hint:"结果很好" },
    { unit:2, clue:"___ of other people", sentence:"Science is not my profession, so if you want to discuss it, you could ______ of other people here who know science better than me.", ans:"pick the brains of", cn:"请教学者", hint:"请教他人" },
    { unit:2, clue:"grades are ___", sentence:"If you feel that your grades or your study skills are ______, you may turn to your teachers for advice.", ans:"not up to par", cn:"达不到标准", hint:"不达标" },
    { unit:2, clue:"teachers who are ___ their work", sentence:"I draw inspiration from many teachers who are ______ their work and try to spread their enthusiasm to their students.", ans:"be passionate about", filled:"passionate about", cn:"热爱", hint:"热爱工作" },
    { unit:2, clue:"always ___ money", sentence:"If one is always ______ money, appearance, and social status, they will unfortunately forget what is most important in their life.", ans:"be obsessed with", filled:"obsessed with", cn:"沉迷于", hint:"沉迷物质" },

    // ── Unit 3 ──
    { unit:3, clue:"___ my creativity", sentence:"The course project that I completed weeks ago has helped me ______ my creativity and intuition which I didn't even realize I had.", ans:"tap into", cn:"挖掘", hint:"挖掘创造力" },
    { unit:3, clue:"many people probably ___", sentence:"Many people probably ______ fast Internet access is almost everywhere \u2013 at home, at work, and even in the most remote areas.", ans:"take it for granted that", cn:"认为…理所当然", hint:"视为当然" },
    { unit:3, clue:"we always ___ the goal", sentence:"It's probably true that we always ______ the goal that we consider challenging but achievable to gain a sense of accomplishment.", ans:"strive for", cn:"努力追求", hint:"努力追求目标" },
    { unit:3, clue:"it's ___ to say", sentence:"It's ______ to say that the kitchen he installed last month is 100 times better, and now I fortunately have the kitchen I dreamed of.", ans:"no exaggeration", cn:"毫不夸张", hint:"毫不夸张" },
    { unit:3, clue:"exam ___ what you learned", sentence:"Since the exam ______ what you have learned, you can expect to see some questions from previous assignments.", ans:"be based on", filled:"is based on", cn:"基于", hint:"基于所学" },
    { unit:3, clue:"journalists ___ daily deadlines", sentence:"I think journalists work in a timely manner and ______ daily deadlines or tight working schedules because they were well trained in this way.", ans:"be accustomed to", filled:"are accustomed to", cn:"习惯于", hint:"习惯截止日期" },
    { unit:3, clue:"___ improving our relations", sentence:"The situation between us is very challenging, but we have to learn how to handle the difficult situation ______ improving our relations.", ans:"for the sake of", cn:"为了", hint:"为了关系" },
    { unit:3, clue:"___ Chinese food since young", sentence:"The award-winning chef says that since he was young, he ______ Chinese food because of its rich ingredients and well-balanced nutrition.", ans:"have a passion for", filled:"has had a passion for", cn:"热爱", hint:"热爱中餐" },

    // ── Unit 4 ──
    { unit:4, clue:"things that ___", sentence:"When I was traveling in China, I would ride my bike slowly, take pictures of the things that ______, and talk to people.", ans:"catch sb's eye", filled:"caught my eye", cn:"吸引眼球", hint:"吸引目光" },
    { unit:4, clue:"___ teach lab techniques", sentence:"As a senior assistant in the lab for quite a few years, I was thrilled to ______ teach lab techniques to the new students.", ans:"be entrusted to", filled:"be entrusted to", cn:"被委托", hint:"受托教学" },
    { unit:4, clue:"spent the afternoon ___", sentence:"It was raining heavily, so she spent the whole afternoon ______ in her dorm room and reading.", ans:"hole up", filled:"holing up", cn:"躲藏", hint:"躲藏起来" },
    { unit:4, clue:"___ high-quality cooperation", sentence:"We will build a closer partnership and ______ high-quality cooperation under the Belt and Road Initiative.", ans:"remain committed to", cn:"保持承诺", hint:"致力于合作" },
    { unit:4, clue:"my efforts ___ in the end", sentence:"I went back to school to get my coaching certification, and my efforts and persistence ______ in the end.", ans:"pay off", filled:"paid off", cn:"成功/回报", hint:"努力有回报" },
    { unit:4, clue:"then ___ to complete", sentence:"She joined the lab as a summer student and then ______ to complete her fourth-year honors thesis before graduation.", ans:"stay on", filled:"stayed on", cn:"继续留下", hint:"继续完成" },
    { unit:4, clue:"traditions that ___", sentence:"The traditions that ______ from generation to generation will surely enrich our culture and be carried forward.", ans:"pass ... down", filled:"are passed down", cn:"传承", hint:"传承传统" },
    { unit:4, clue:"countries ___ medicines", sentence:"To fight against the common health crisis, China has made great efforts to help other countries ______ medicines.", ans:"in urgent need of", cn:"急需", hint:"急需药品" },
];

// 选词填空专用干扰项池（不作为题目出现，只用于生成选项）
// 每个词尽量与正确答案在拼写、词尾或词性上相近，增强干扰性
const mcDistractors = [
    // Unit 1 相关干扰
    { ans:"condense", cn:"压缩" },
    { ans:"confess", cn:"承认" },
    { ans:"consent", cn:"同意" },
    { ans:"contend", cn:"竞争" },
    { ans:"content", cn:"内容" },
    { ans:"context", cn:"语境" },
    { ans:"contract", cn:"合同/收缩" },
    { ans:"contrast", cn:"对比" },
    { ans:"exceed", cn:"超过" },
    { ans:"proceed", cn:"继续" },
    { ans:"succeed", cn:"成功" },
    { ans:"recede", cn:"后退" },
    { ans:"concede", cn:"让步" },
    { ans:"asset", cn:"资产" },
    { ans:"access", cn:"通道/使用" },
    { ans:"assess", cn:"评估" },
    { ans:"assist", cn:"帮助" },
    { ans:"assign", cn:"分配" },
    { ans:"assume", cn:"假设" },
    { ans:"assure", cn:"保证" },
    { ans:"deficit", cn:"赤字" },
    { ans:"defect", cn:"缺陷" },
    { ans:"defense", cn:"防御" },
    { ans:"define", cn:"定义" },
    { ans:"deny", cn:"否认" },
    { ans:"deduce", cn:"推断" },
    { ans:"distinguish", cn:"区分" },
    { ans:"extinguish", cn:"熄灭" },
    { ans:"distribute", cn:"分配" },
    { ans:"disturb", cn:"打扰" },
    { ans:"distort", cn:"扭曲" },
    { ans:"competent", cn:"能胜任的" },
    { ans:"compete", cn:"竞争" },
    { ans:"compile", cn:"编译" },
    { ans:"compel", cn:"强迫" },
    { ans:"complete", cn:"完成" },
    { ans:"complex", cn:"复杂的" },
    { ans:"comprehend", cn:"理解" },
    { ans:"compromise", cn:"妥协" },
    { ans:"adequately", cn:"充分地" },
    { ans:"adequate", cn:"足够的" },
    { ans:"accurately", cn:"精确地" },
    { ans:"approximately", cn:"大约" },
    { ans:"absolutely", cn:"绝对地" },
    { ans:"actively", cn:"积极地" },
    { ans:"attractively", cn:"有吸引力地" },
    { ans:"adjust", cn:"调整" },
    { ans:"adapt", cn:"适应" },
    { ans:"adopt", cn:"采纳" },
    { ans:"admit", cn:"承认" },
    { ans:"advance", cn:"前进" },
    { ans:"advantage", cn:"优势" },
    { ans:"precise", cn:"精确的" },
    { ans:"precisely", cn:"精确地" },
    { ans:"concise", cn:"简明的" },
    { ans:"precious", cn:"珍贵的" },
    { ans:"previous", cn:"之前的" },
    { ans:"proficiency", cn:"熟练" },
    { ans:"efficiency", cn:"效率" },
    { ans:"sufficiency", cn:"充足" },
    { ans:"deficiency", cn:"不足" },
    { ans:"frequency", cn:"频率" },

    // Unit 2 相关干扰
    { ans:"prolonged", cn:"长期的" },
    { ans:"belonged", cn:"属于" },
    { ans:"prosperous", cn:"繁荣的" },
    { ans:"prominent", cn:"杰出的" },
    { ans:"promising", cn:"有前途的" },
    { ans:"release", cn:"释放" },
    { ans:"relieve", cn:"缓解" },
    { ans:"relate", cn:"联系" },
    { ans:"relax", cn:"放松" },
    { ans:"relay", cn:"接力" },
    { ans:"rely", cn:"依赖" },
    { ans:"artistic", cn:"艺术的" },
    { ans:"realistic", cn:"现实的" },
    { ans:"optimistic", cn:"乐观的" },
    { ans:"domestic", cn:"国内的" },
    { ans:"enthusiastic", cn:"热情的" },
    { ans:"browse", cn:"浏览" },
    { ans:"brow", cn:"眉毛" },
    { ans:"brave", cn:"勇敢" },
    { ans:"brake", cn:"刹车" },
    { ans:"brand", cn:"品牌" },
    { ans:"magnificence", cn:"宏伟" },
    { ans:"significance", cn:"重要性" },
    { ans:"elegance", cn:"优雅" },
    { ans:"tolerance", cn:"容忍" },
    { ans:"brilliance", cn:"辉煌" },
    { ans:"option", cn:"选项" },
    { ans:"adoption", cn:"采纳" },
    { ans:"portion", cn:"部分" },
    { ans:"notion", cn:"概念" },
    { ans:"motion", cn:"运动" },
    { ans:"confirm", cn:"确认" },
    { ans:"conform", cn:"符合" },
    { ans:"confine", cn:"限制" },
    { ans:"confront", cn:"面对" },
    { ans:"confuse", cn:"困惑" },
    { ans:"reputable", cn:"声誉好的" },
    { ans:"reputation", cn:"声誉" },
    { ans:"reasonable", cn:"合理的" },
    { ans:"reliable", cn:"可靠的" },
    { ans:"remarkable", cn:"非凡的" },
    { ans:"respectable", cn:"可敬的" },
    { ans:"provoke", cn:"引发" },
    { ans:"invoke", cn:"援引" },
    { ans:"revoke", cn:"撤销" },
    { ans:"evoke", cn:"唤起" },
    { ans:"convoke", cn:"召集" },
    { ans:"aspiration", cn:"志向" },
    { ans:"inspiration", cn:"灵感" },
    { ans:"respiration", cn:"呼吸" },
    { ans:"perspiration", cn:"汗水" },
    { ans:"expiration", cn:"到期" },

    // Unit 3 相关干扰
    { ans:"flexible", cn:"灵活的" },
    { ans:"feasible", cn:"可行的" },
    { ans:"visible", cn:"可见的" },
    { ans:"sensible", cn:"明智的" },
    { ans:"responsible", cn:"负责的" },
    { ans:"parallel", cn:"平行" },
    { ans:"paralyze", cn:"麻痹" },
    { ans:"parameter", cn:"参数" },
    { ans:"paradox", cn:"悖论" },
    { ans:"paragraph", cn:"段落" },
    { ans:"assign", cn:"分配" },
    { ans:"resign", cn:"辞职" },
    { ans:"design", cn:"设计" },
    { ans:"signal", cn:"信号" },
    { ans:"exhibit", cn:"展现" },
    { ans:"inhibit", cn:"抑制" },
    { ans:"prohibit", cn:"禁止" },
    { ans:"habit", cn:"习惯" },
    { ans:"exile", cn:"流放" },
    { ans:"exist", cn:"存在" },
    { ans:"persistence", cn:"坚持" },
    { ans:"resistance", cn:"抵抗" },
    { ans:"assistance", cn:"帮助" },
    { ans:"existence", cn:"存在" },
    { ans:"consistence", cn:"一致性" },
    { ans:"stunning", cn:"令人惊叹的" },
    { ans:"striking", cn:"显著的" },
    { ans:"striving", cn:"努力的" },
    { ans:"recruit", cn:"招募" },
    { ans:"recycle", cn:"回收" },
    { ans:"recall", cn:"回忆" },
    { ans:"reclaim", cn:" reclaim" },
    { ans:"recover", cn:"恢复" },
    { ans:"endure", cn:"忍受" },
    { ans:"ensure", cn:"确保" },
    { ans:"endanger", cn:"危及" },
    { ans:"enforce", cn:"执行" },
    { ans:"engage", cn:"从事" },
    { ans:"enlarge", cn:"扩大" },
    { ans:"vigorous", cn:"剧烈的" },
    { ans:"rigorous", cn:"严格的" },
    { ans:"vulnerable", cn:"脆弱的" },
    { ans:"ridiculous", cn:"荒谬的" },
    { ans:"internal", cn:"内心的" },
    { ans:"eternal", cn:"永恒的" },
    { ans:"external", cn:"外部的" },
    { ans:"interval", cn:"间隔" },
    { ans:"infernal", cn:"地狱的" },

    // Unit 4 相关干扰
    { ans:"typical", cn:"典型的" },
    { ans:"typically", cn:"通常" },
    { ans:"tropical", cn:"热带的" },
    { ans:"topical", cn:"时事的" },
    { ans:"critical", cn:"关键的" },
    { ans:"practical", cn:"实用的" },
    { ans:"survey", cn:"调查" },
    { ans:"survive", cn:"幸存" },
    { ans:"surface", cn:"表面" },
    { ans:"surround", cn:"包围" },
    { ans:"surrender", cn:"投降" },
    { ans:"random", cn:"随机的" },
    { ans:"ransom", cn:"赎金" },
    { ans:"rational", cn:"理性的" },
    { ans:"radical", cn:"激进的" },
    { ans:"maximize", cn:"最大化" },
    { ans:"minimize", cn:"最小化" },
    { ans:"optimize", cn:"优化" },
    { ans:"realize", cn:"意识到" },
    { ans:"recognize", cn:"认出" },
    { ans:"fulfill", cn:"完成" },
    { ans:"fulfilled", cn:"满足的" },
    { ans:"fill", cn:"填满" },
    { ans:"resolute", cn:"坚决的" },
    { ans:"resolutely", cn:"坚决地" },
    { ans:"absolute", cn:"绝对的" },
    { ans:"dissolute", cn:"放荡的" },
    { ans:"strategic", cn:"战略的" },
    { ans:"strategically", cn:"战略地" },
    { ans:"tactic", cn:"战术" },
    { ans:"systematic", cn:"系统的" },
    { ans:"diplomatic", cn:"外交的" },
    { ans:"exceptional", cn:"非凡的" },
    { ans:"exceptionally", cn:"异常地" },
    { ans:"acceptable", cn:"可接受的" },
    { ans:"accessible", cn:"可接近的" },
    { ans:"perceptible", cn:"可察觉的" },
    { ans:"chase", cn:"追逐" },
    { ans:"purchase", cn:"购买" },
    { ans:"cease", cn:"停止" },
    { ans:"cheese", cn:"奶酪" },
    { ans:"explicit", cn:"明确的" },
    { ans:"implicit", cn:"含蓄的" },
    { ans:"explicate", cn:"解释" },
    { ans:"explode", cn:"爆炸" },
    { ans:"exploit", cn:"利用" },
];

// 短语完形专用干扰项池（不作为题目出现，只用于生成选项）
// 每个短语尽量与正确答案在拼写、结构或词尾上相近，增强干扰性
const expDistractors = [
    // 含 be / become / get 的系表结构
    { ans:"be obliged to", cn:"有义务" },
    { ans:"be forced to", cn:"被迫" },
    { ans:"be likely to", cn:"可能" },
    { ans:"be willing to", cn:"愿意" },
    { ans:"be reluctant to", cn:"不情愿" },
    { ans:"be supposed to", cn:"应该" },
    { ans:"be expected to", cn:"被期望" },
    { ans:"be required to", cn:"被要求" },
    { ans:"be allowed to", cn:"被允许" },
    { ans:"be able to", cn:"能够" },
    { ans:"be used to", cn:"习惯于" },
    { ans:"be accustomed to", cn:"习惯于" },
    { ans:"be addicted to", cn:"沉迷于" },
    { ans:"be exposed to", cn:"暴露于" },
    { ans:"be committed to", cn:"致力于" },
    { ans:"be dedicated to", cn:"致力于" },
    { ans:"be devoted to", cn:"致力于" },
    { ans:"be attracted to", cn:"被吸引" },
    { ans:"be opposed to", cn:"反对" },
    { ans:"be subject to", cn:"受制于" },
    { ans:"be sensitive to", cn:"对…敏感" },
    { ans:"be similar to", cn:"与…相似" },
    { ans:"be essential to", cn:"对…必要" },
    { ans:"be beneficial to", cn:"有益于" },
    { ans:"be harmful to", cn:"有害于" },
    { ans:"be grateful to", cn:"感激" },
    { ans:"be loyal to", cn:"忠诚于" },
    { ans:"be relevant to", cn:"与…相关" },
    { ans:"be attached to", cn:"依附于" },
    { ans:"be related to", cn:"与…有关" },
    { ans:"be due to", cn:"由于" },
    { ans:"be opposed to", cn:"反对" },
    { ans:"be prone to", cn:"易于" },
    { ans:"be vulnerable to", cn:"易受…影响" },
    { ans:"be resistant to", cn:"抵抗" },

    // get / become 系表或动作短语
    { ans:"get used to", cn:"习惯于" },
    { ans:"get accustomed to", cn:"习惯于" },
    { ans:"get rid of", cn:"摆脱" },
    { ans:"get hold of", cn:"抓住" },
    { ans:"get in touch with", cn:"联系" },
    { ans:"get along with", cn:"相处" },
    { ans:"get away with", cn:"侥幸逃脱" },
    { ans:"get down to", cn:"开始认真做" },
    { ans:"get out of", cn:"逃避" },
    { ans:"get over", cn:"克服" },
    { ans:"get up", cn:"起床" },
    { ans:"get off", cn:"下车" },
    { ans:"get on", cn:"上车" },
    { ans:"get into", cn:"进入" },
    { ans:"get rid of", cn:"摆脱" },
    { ans:"get tired of", cn:"厌倦" },
    { ans:"get bored with", cn:"厌倦" },
    { ans:"become aware of", cn:"意识到" },
    { ans:"become fond of", cn:"喜欢" },
    { ans:"become tired of", cn:"厌倦" },
    { ans:"become used to", cn:"习惯于" },

    // look / see / watch 相关
    { ans:"look upon ... as", cn:"把…视为" },
    { ans:"look on ... as", cn:"把…看作" },
    { ans:"look forward to", cn:"期待" },
    { ans:"look after", cn:"照顾" },
    { ans:"look for", cn:"寻找" },
    { ans:"look into", cn:"调查" },
    { ans:"look out", cn:"小心" },
    { ans:"look up", cn:"查阅" },
    { ans:"look up to", cn:"尊敬" },
    { ans:"look down on", cn:"轻视" },
    { ans:"look around", cn:"环顾" },
    { ans:"see ... as", cn:"把…视为" },
    { ans:"regard ... as", cn:"把…视为" },
    { ans:"think of ... as", cn:"认为…是" },
    { ans:"refer to ... as", cn:"把…称作" },
    { ans:"treat ... as", cn:"把…当作" },
    { ans:"take ... as", cn:"把…当作" },
    { ans:"view ... as", cn:"把…看作" },

    // run / come / go / make 短语
    { ans:"run into", cn:"偶遇" },
    { ans:"run across", cn:"偶遇" },
    { ans:"run after", cn:"追逐" },
    { ans:"run out of", cn:"用完" },
    { ans:"run over", cn:"碾过" },
    { ans:"run through", cn:"浏览" },
    { ans:"come across", cn:"偶遇" },
    { ans:"come up with", cn:"想出" },
    { ans:"come down with", cn:"患上" },
    { ans:"come out of", cn:"从…出来" },
    { ans:"come to terms with", cn:"接受" },
    { ans:"go through", cn:"经历" },
    { ans:"go over", cn:"复习" },
    { ans:"go on", cn:"继续" },
    { ans:"go off", cn:"爆炸/离开" },
    { ans:"go out", cn:"外出" },
    { ans:"go by", cn:"依照/流逝" },
    { ans:"go back to", cn:"回到" },
    { ans:"go in for", cn:"从事" },
    { ans:"make out", cn:"辨认出" },
    { ans:"make up", cn:"组成/编造" },
    { ans:"make up for", cn:"弥补" },
    { ans:"make sense of", cn:"理解" },
    { ans:"make fun of", cn:"取笑" },
    { ans:"make use of", cn:"利用" },
    { ans:"make sure of", cn:"确保" },

    // take 短语
    { ans:"take it for granted that", cn:"认为…理所当然" },
    { ans:"take ... for granted", cn:"认为…理所当然" },
    { ans:"take advantage of", cn:"利用" },
    { ans:"take care of", cn:"照顾" },
    { ans:"take charge of", cn:"负责" },
    { ans:"take part in", cn:"参加" },
    { ans:"take place", cn:"发生" },
    { ans:"take over", cn:"接管" },
    { ans:"take in", cn:"吸收" },
    { ans:"take on", cn:"承担" },
    { ans:"take off", cn:"起飞" },
    { ans:"take up", cn:"开始从事" },
    { ans:"take away", cn:"拿走" },
    { ans:"take back", cn:"收回" },
    { ans:"take down", cn:"记下" },
    { ans:"take after", cn:"像" },
    { ans:"take against", cn:"反对" },
    { ans:"take to", cn:"喜欢上" },

    // 认真对待 / 开始做
    { ans:"get serious about", cn:"认真对待" },
    { ans:"be serious about", cn:"对…认真" },
    { ans:"be careful about", cn:"对…小心" },
    { ans:"be concerned about", cn:"担心" },
    { ans:"be worried about", cn:"担心" },
    { ans:"be anxious about", cn:"焦虑" },
    { ans:"be particular about", cn:"挑剔" },
    { ans:"be curious about", cn:"好奇" },
    { ans:"be enthusiastic about", cn:"对…热情" },
    { ans:"be excited about", cn:"对…兴奋" },
    { ans:"be mad about", cn:"对…狂热" },
    { ans:"be crazy about", cn:"对…痴迷" },

    // 区分 / 辨别
    { ans:"distinguish between", cn:"区分" },
    { ans:"distinguish ... from", cn:"区分" },
    { ans:"tell ... from", cn:"辨别" },
    { ans:"tell ... apart", cn:"分辨" },
    { ans:"separate ... from", cn:"分离" },
    { ans:"differentiate between", cn:"区分" },
    { ans:"make a distinction between", cn:"区分" },
    { ans:"draw a distinction between", cn:"区分" },

    // 对…反感 / 过敏
    { ans:"be allergic to", cn:"对…过敏/反感" },
    { ans:"be sensitive to", cn:"对…敏感" },
    { ans:"be immune to", cn:"对…免疫" },
    { ans:"be indifferent to", cn:"对…漠不关心" },
    { ans:"be opposed to", cn:"反对" },
    { ans:"be averse to", cn:"厌恶" },

    // 跟上 / 迷失
    { ans:"get lost", cn:"迷路" },
    { ans:"get left behind", cn:"被落下" },
    { ans:"keep up with", cn:"跟上" },
    { ans:"catch up with", cn:"赶上" },
    { ans:"fall behind", cn:"落后" },
    { ans:"keep pace with", cn:"并驾齐驱" },
    { ans:"lose track of", cn:"失去联系" },
    { ans:"keep in touch with", cn:"保持联系" },

    // 敬畏 / 情绪
    { ans:"in awe", cn:"敬畏" },
    { ans:"in fear", cn:"恐惧" },
    { ans:"in panic", cn:"恐慌" },
    { ans:"in tears", cn:"流泪" },
    { ans:"in despair", cn:"绝望" },
    { ans:"in surprise", cn:"惊讶" },
    { ans:"in shock", cn:"震惊" },
    { ans:"in doubt", cn:"怀疑" },
    { ans:"in trouble", cn:"麻烦" },
    { ans:"in danger", cn:"危险" },
    { ans:"in silence", cn:"沉默" },

    // 提出 / 抛出
    { ans:"throw ... out", cn:"抛出" },
    { ans:"put forward", cn:"提出" },
    { ans:"bring up", cn:"提出/抚养" },
    { ans:"bring forward", cn:"提出" },
    { ans:"come up with", cn:"想出" },
    { ans:"put out", cn:"熄灭" },
    { ans:"set out", cn:"出发" },
    { ans:"carry out", cn:"执行" },
    { ans:"work out", cn:"解决" },
    { ans:"figure out", cn:"弄清楚" },
    { ans:"find out", cn:"发现" },
    { ans:"point out", cn:"指出" },
    { ans:"set off", cn:"出发" },
    { ans:"give off", cn:"散发" },

    // 让某人失望
    { ans:"let sb. down", cn:"让某人失望" },
    { ans:"let ... down", cn:"让…失望" },
    { ans:"live up to", cn:"不辜负" },
    { ans:"look up to", cn:"尊敬" },
    { ans:"turn down", cn:"拒绝" },
    { ans:"set down", cn:"放下" },
    { ans:"calm down", cn:"冷静" },
    { ans:"slow down", cn:"放慢" },
    { ans:"break down", cn:"出故障" },

    // 结果 / 变成
    { ans:"turn out", cn:"结果证明" },
    { ans:"turn into", cn:"变成" },
    { ans:"turn up", cn:"出现" },
    { ans:"turn down", cn:"拒绝" },
    { ans:"turn over", cn:"翻转" },
    { ans:"turn around", cn:"转身" },
    { ans:"turn in", cn:"上交" },
    { ans:"turn to", cn:"求助于" },
    { ans:"work out", cn:"结果是" },
    { ans:"figure out", cn:"弄明白" },
    { ans:"find out", cn:"查明" },
    { ans:"point out", cn:"指出" },

    // 请教 / 思考
    { ans:"pick the brains of", cn:"请教" },
    { ans:"ask the advice of", cn:"征求…意见" },
    { ans:"seek advice from", cn:"向…请教" },
    { ans:"learn from", cn:"向…学习" },
    { ans:"benefit from", cn:"从…受益" },
    { ans:"hear from", cn:"收到…来信" },
    { ans:"keep ... in mind", cn:"记住" },
    { ans:"bear ... in mind", cn:"记住" },

    // 达到标准 / 合格
    { ans:"not up to par", cn:"不达标" },
    { ans:"up to standard", cn:"达到标准" },
    { ans:"up to date", cn:"最新的" },
    { ans:"up to ...", cn:"取决于" },
    { ans:"meet the standard", cn:"达到标准" },
    { ans:"reach the standard", cn:"达到标准" },
    { ans:"live up to expectations", cn:"不负期望" },

    // 热爱 / 沉迷
    { ans:"be passionate about", cn:"热爱" },
    { ans:"be enthusiastic about", cn:"热情" },
    { ans:"be fond of", cn:"喜欢" },
    { ans:"be keen on", cn:"热衷于" },
    { ans:"be interested in", cn:"感兴趣" },
    { ans:"be absorbed in", cn:"全神贯注于" },
    { ans:"be buried in", cn:"埋头于" },
    { ans:"be occupied with", cn:"忙于" },
    { ans:"be engaged in", cn:"从事于" },
    { ans:"be involved in", cn:"参与" },
    { ans:"be obsessed with", cn:"沉迷于" },
    { ans:"be preoccupied with", cn:"全神贯注于" },

    // 挖掘 / 利用
    { ans:"tap into", cn:"挖掘" },
    { ans:"dip into", cn:"动用" },
    { ans:"dig into", cn:"深入钻研" },
    { ans:"get into", cn:"进入" },
    { ans:"look into", cn:"调查" },
    { ans:"break into", cn:"闯入" },
    { ans:"burst into", cn:"突然…起来" },
    { ans:"give in to", cn:"屈服于" },

    // 努力追求 / 争取
    { ans:"strive for", cn:"努力追求" },
    { ans:"aim for", cn:"力求" },
    { ans:"go for", cn:"争取" },
    { ans:"work for", cn:"为…工作" },
    { ans:"fight for", cn:"为…奋斗" },
    { ans:"long for", cn:"渴望" },
    { ans:"yearn for", cn:"渴望" },
    { ans:"search for", cn:"寻找" },
    { ans:"apply for", cn:"申请" },
    { ans:"care for", cn:"照顾" },
    { ans:"stand for", cn:"代表" },
    { ans:"call for", cn:"要求" },
    { ans:"pay for", cn:"为…付费" },
    { ans:"wait for", cn:"等待" },
    { ans:"prepare for", cn:"为…准备" },

    // 毫不夸张
    { ans:"no exaggeration", cn:"毫不夸张" },
    { ans:"without exaggeration", cn:"毫不夸张" },
    { ans:"beyond exaggeration", cn:"毫不夸张" },

    // 基于
    { ans:"be based on", cn:"基于" },
    { ans:"be founded on", cn:"建立在…上" },
    { ans:"be built on", cn:"建立在" },
    { ans:"depend on", cn:"依赖" },
    { ans:"rely on", cn:"依靠" },
    { ans:"count on", cn:"指望" },

    // 习惯于 / 适应
    { ans:"be accustomed to", cn:"习惯于" },
    { ans:"get accustomed to", cn:"习惯于" },
    { ans:"be used to", cn:"习惯于" },
    { ans:"get used to", cn:"习惯于" },

    // 为了
    { ans:"for the sake of", cn:"为了" },
    { ans:"for the purpose of", cn:"为了" },
    { ans:"for the benefit of", cn:"为了…的利益" },
    { ans:"in favor of", cn:"支持" },
    { ans:"in place of", cn:"代替" },
    { ans:"instead of", cn:"代替" },
    { ans:"because of", cn:"因为" },
    { ans:"by means of", cn:"通过" },
    { ans:"by way of", cn:"经由" },
    { ans:"with regard to", cn:"关于" },
    { ans:"in terms of", cn:"就…而言" },
    { ans:"in spite of", cn:"尽管" },
    { ans:"regardless of", cn:"不管" },
    { ans:"on behalf of", cn:"代表" },

    // 热爱（have a passion for）
    { ans:"have a passion for", cn:"热爱" },
    { ans:"have a taste for", cn:"喜欢" },
    { ans:"have a preference for", cn:"偏爱" },
    { ans:"have a gift for", cn:"有…天赋" },
    { ans:"have a talent for", cn:"有…天赋" },
    { ans:"have a desire for", cn:"渴望" },
    { ans:"have a eye for", cn:"善于欣赏" },
    { ans:"have a nose for", cn:"对…敏感" },

    // 吸引眼球
    { ans:"catch sb's eye", cn:"吸引眼球" },
    { ans:"catch one's eye", cn:"吸引眼球" },
    { ans:"draw one's attention", cn:"吸引注意" },
    { ans:"attract one's attention", cn:"吸引注意" },
    { ans:"draw one's interest", cn:"引起兴趣" },
    { ans:"appeal to", cn:"吸引" },

    // 被委托
    { ans:"be entrusted to", cn:"被委托" },
    { ans:"be assigned to", cn:"被分配给" },
    { ans:"be devoted to", cn:"致力于" },
    { ans:"be confined to", cn:"被限制于" },
    { ans:"be limited to", cn:"被限制于" },
    { ans:"be reduced to", cn:"沦为" },

    // 躲藏
    { ans:"hole up", cn:"躲藏" },
    { ans:"hide away", cn:"躲藏" },
    { ans:"shut oneself away", cn:"闭门不出" },
    { ans:"stay in", cn:"待在家里" },
    { ans:"keep in", cn:"抑制" },
    { ans:"hold in", cn:"抑制" },

    // 保持承诺 / 致力于
    { ans:"remain committed to", cn:"保持承诺" },
    { ans:"be committed to", cn:"致力于" },
    { ans:"stick to", cn:"坚持" },
    { ans:"hold on to", cn:"坚持" },
    { ans:"keep to", cn:"遵守" },
    { ans:"adhere to", cn:"坚持" },
    { ans:"cling to", cn:"固守" },
    { ans:"abide by", cn:"遵守" },
    { ans:"comply with", cn:"遵守" },
    { ans:"conform to", cn:"符合" },

    // 成功 / 回报
    { ans:"pay off", cn:"成功/回报" },
    { ans:"pay back", cn:"偿还" },
    { ans:"pay for", cn:"为…付费" },
    { ans:"pay out", cn:"付出" },
    { ans:"pay up", cn:"付清" },
    { ans:"work out", cn:"解决" },
    { ans:"turn out", cn:"结果是" },
    { ans:"come off", cn:"成功" },
    { ans:"pay dividends", cn:"带来回报" },

    // 继续留下
    { ans:"stay on", cn:"继续留下" },
    { ans:"remain on", cn:"继续" },
    { ans:"keep on", cn:"继续" },
    { ans:"carry on", cn:"继续" },
    { ans:"go on", cn:"继续" },
    { ans:"move on", cn:"继续前进" },
    { ans:"hold on", cn:"坚持" },
    { ans:"hang on", cn:"坚持" },

    // 传承
    { ans:"pass ... down", cn:"传承" },
    { ans:"hand ... down", cn:"传下来" },
    { ans:"pass ... on", cn:"传递" },
    { ans:"hand ... on", cn:"传下去" },
    { ans:"give ... away", cn:"赠送" },
    { ans:"leave ... behind", cn:"留下" },
    { ans:"carry forward", cn:"发扬光大" },

    // 急需
    { ans:"in urgent need of", cn:"急需" },
    { ans:"in great need of", cn:"急需" },
    { ans:"in desperate need of", cn:"急需" },
    { ans:"in need of", cn:"需要" },
    { ans:"in search of", cn:"寻找" },
    { ans:"in charge of", cn:"负责" },
    { ans:"in possession of", cn:"拥有" },
    { ans:"in favor of", cn:"支持" },
];

// 中译英数据 (transData)
const transData = [
    { id:0, chn:"众所周知，中国书法是一门独特的艺术，也是世界上独一无二的艺术瑰宝。", eng:"As is well known, Chinese calligraphy is a unique art and an unparalleled art treasure in the world.", keys:"well known, calligraphy, unique art, unparalleled, art treasure" },
    { id:1, chn:"汉字在漫长的演变过程中，始终起着交流思想、传承文化的重要作用。", eng:"In their long evolution, Chinese characters have always played a key role in communication and cultural transmission.", keys:"evolution, Chinese characters, played, communication, cultural transmission" },
    { id:2, chn:"很显然，中国书法的形成、发展与汉字的演变存在着密不可分的关系。", eng:"Clearly, the rise and development of Chinese calligraphy are closely tied to the evolution of Chinese characters.", keys:"rise, development, calligraphy, closely tied, evolution, characters" },
    { id:3, chn:"改革开放以来，中国的教育事业得到了快速发展，并取得了引人瞩目的成就。", eng:"Since the reform and opening up, China\u2019s education has grown fast and made remarkable achievements.", keys:"reform and opening up, education, grown fast, remarkable achievements" },
    { id:4, chn:"中国的教育成就主要反映在九年义务教育的全面普及和高等教育大众化的实现。", eng:"China\u2019s educational achievements are seen in the spread of nine-year compulsory education and the rise of mass higher education.", keys:"educational achievements, spread, compulsory education, mass higher education" },
    { id:5, chn:"我们将深入实施科教兴国战略，坚持教育优先发展，为党育人、为国育才，全面提高人才自主培养质量。", eng:"We will pursue a strategy of developing China through science and education, give priority to education, cultivate talent for the Party and the nation, and improve our ability to nurture talent on our own.", keys:"developing China, science and education, priority to education, cultivate talent, nurture talent" },
    { id:6, chn:"如今，很多年轻人不再只选择稳定的工作，他们更愿意自主创业，依靠自己的智慧和努力去证明他们的自我价值。", eng:"Today, many young people no longer choose only stable jobs. They prefer to start their own businesses and prove their worth through their wisdom and hard work.", keys:"stable jobs, start businesses, prove their worth, wisdom, hard work" },
    { id:7, chn:"创业者的成功不但会创造财富，增加就业机会，改善大家的生活，而且从长远来看，对于我们的国家也是一件好事。", eng:"The success of entrepreneurs creates wealth, provides jobs, and improves lives. In the long run, it also benefits our country.", keys:"creates wealth, provides jobs, improves lives, benefits, in the long run" },
    { id:8, chn:"中国政府大力鼓励和支持创业和创新，这会进一步激发年轻人的热情，增强他们的信心。", eng:"The Chinese government strongly supports entrepreneurship and innovation. This further sparks young people\u2019s passion and boosts their confidence.", keys:"supports, entrepreneurship, innovation, sparks passion, boosts confidence" },
    { id:9, chn:"丝绸之路是中国古代的交通线路网络，也是中国最早用于国际贸易和文化交流的渠道。", eng:"The Silk Road was an ancient transport network in China and the country\u2019s earliest channel for international trade and cultural exchange.", keys:"Silk Road, transport network, channel, international trade, cultural exchange" },
    { id:10, chn:"在古代，丝绸之路有效地促进了各国之间经济文化的交流，从而大大推动了世界文明的进程。", eng:"In ancient times, the Silk Road boosted trade and cultural ties between nations, thus advancing world civilization.", keys:"boosted, trade and cultural ties, advancing, world civilization" },
    { id:11, chn:"在新的历史条件下，中国提出了以合作共赢为核心的\u201C一带一路\u201D倡议，得到了沿线各国的积极响应。", eng:"In the new era, China put forward the Belt and Road Initiative, centered on win-win cooperation, and it has received a warm response from countries along the route.", keys:"Belt and Road Initiative, win-win cooperation, warm response" },
];
